# Generated by Django 3.2.4 on 2021-07-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='DESCRIPTION',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='UPDATED',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='resign_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='DESCRIPTION',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='DESCRIPTION',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='UPDATED',
            field=models.DateField(null=True),
        ),
    ]
