# Generated by Django 3.2.4 on 2021-07-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210714_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.IntegerField()),
                ('event_date', models.DateTimeField(auto_now=True)),
                ('event_location', models.CharField(max_length=200)),
                ('event_desc', models.CharField(max_length=200)),
                ('oldperson_name', models.CharField(max_length=50)),
                ('face_list', models.JSONField(null=True)),
            ],
        ),
    ]
