# Generated by Django 3.2.4 on 2021-07-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_event_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer_info',
            old_name='name',
            new_name='username',
        ),
    ]
