# Generated by Django 3.2.4 on 2021-07-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210714_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sys_user',
            name='UPDATED',
            field=models.DateField(null=True),
        ),
    ]
