# Generated by Django 3.2.4 on 2021-07-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_sys_user_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sys_user',
            name='EMAIL',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='MOBILE',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='PHONE',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='REAL_NAME',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='SEX',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
